### ISSUE TITLE
Empty list while running this for olx.bg or olx.in

### ISSUE THREAD

**Issue by iamshreeram** [ilovethensa/olx-scraper#1]
@ilovethensa, When executing this as a binary for the websites **olx.bg** or **olx.in**, I am obtaining an empty list.

<img width="536" alt="image" src="https://github.com/ilovethensa/olx-scraper/assets/7752805/d59ffc6c-e22f-41f7-a17f-19a83b7f686e">

**Comment by iamshreeram** [comment]
Hi there @ilovethensa, that's great to hear! The issue with olx.bg has been resolved in [this](https://github.com/ilovethensa/olx-scraper/commit/1391896f9fb2daf19c6a90e7b11be62de44c41a6) commit. 

Could you please confirm if it can also be adapted to work for **olx.in** or provide any necessary details to make it compatible with **olx.in**? 

What I'm seeing for olx.in - 
<img width="558" alt="image" src="https://github.com/ilovethensa/olx-scraper/assets/7752805/589b20b0-ec00-4569-a973-7305ca56c71d">



It would be fantastic if the option to choose between **olx.bg** and **olx.in** could be added as an input parameter, thus turning it into a universal olx scraper.

**Comment by ilovethensa** [comment]
> Hi there @ilovethensa, that's great to hear! The issue with olx.bg has been resolved in [this](https://github.com/ilovethensa/olx-scraper/commit/1391896f9fb2daf19c6a90e7b11be62de44c41a6) commit. 
> 
> Could you please confirm if it can also be adapted to work for **olx.in** or provide any necessary details to make it compatible with **olx.in**? 
> 
> What I'm seeing for olx.in - 
> <img width="558" alt="image" src="https://github.com/ilovethensa/olx-scraper/assets/7752805/589b20b0-ec00-4569-a973-7305ca56c71d">
> 
> 
> 
> It would be fantastic if the option to choose between **olx.bg** and **olx.in** could be added as an input parameter, thus turning it into a universal olx scraper.
> 
> 

I'll see what I can do
